In [1]:
import numpy as np
import pandas as pd
import os

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

from scipy.special import rel_entr
from scipy.stats import entropy
import scipy.stats
import math
import warnings 
warnings.filterwarnings("ignore") 

from sklearn.metrics.cluster import normalized_mutual_info_score, adjusted_rand_score

In [2]:
# 使用GPU
os.environ["CUDA_VISIBLE_DEVICES"]="1"

In [3]:
! nvidia-smi

Tue Jun 28 01:24:14 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 32%   41C    P8    21W / 260W |     22MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| 30%   38C    P8    24W / 260W |   1537MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      6976      G   /usr/lib/xorg/Xorg                  9MiB |
|    0   N/A  N/A      7277      G   /usr/bin/gnome-shell                7MiB |
|    1   N/A  N/A      6976      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A     29483      C   ...nda/envs/assa/bin/python3     1529MiB |
+-----------------------------------------------------------------------------+

# MongoDB

In [4]:
from pymongo import MongoClient
import pymongo

In [5]:
mongoURI = "mongodb://%s:%s@%s/%s?authMechanism=SCRAM-SHA-1" % ("eva", "eva_30241", "140.117.69.70:30241", "eva")

try:
    conn = pymongo.MongoClient(mongoURI)
    db = conn.eva
    # db_de = db.patent_de
    # db_us = db.patent_us
    # db_cn = db.patent_cn

    db_rm_cn_2019 = db.rm_patent_cn_2019
    db_rm_us_2019 = db.rm_patent_us_2019
    db_rm_de_2019 = db.rm_patent_de_2019

    
except errors.ConnectionFailure as err:
    print(err)

# 2019

## Company數量

In [6]:
data_assignee = db_rm_de_2019.aggregate([
    {"$unwind" : "$current_assignee"},
    {"$group" : {"_id" : "$current_assignee", "count":{"$sum":1}}},
    {"$sort": {"count":-1}},
    {"$limit":30}
])

ls_company = []
ls_count = []
for data in data_assignee:
    # print(data["_id"],data["count"])
    ls_company.append(data["_id"])
    ls_count.append(data["count"])

In [7]:
df_family_de = pd.DataFrame((zip(ls_company, ls_count)), columns = ['company', 'count'])

In [8]:
data_assignee = db_rm_cn_2019.aggregate([
    {"$unwind" : "$current_assignee"},
    {"$group" : {"_id" : "$current_assignee", "count":{"$sum":1}}},
    {"$sort": {"count":-1}},
    {"$limit":30}
])

ls_company = []
ls_count = []
for data in data_assignee:
    # print(data["_id"],data["count"])
    ls_company.append(data["_id"])
    ls_count.append(data["count"])
    
df_family_cn = pd.DataFrame((zip(ls_company, ls_count)), columns = ['company', 'count'])

In [9]:
data_assignee = db_rm_us_2019.aggregate([
    {"$unwind" : "$current_assignee"},
    {"$group" : {"_id" : "$current_assignee", "count":{"$sum":1}}},
    {"$sort": {"count":-1}},
    {"$limit":30}
])

ls_company = []
ls_count = []
for data in data_assignee:
    # print(data["_id"],data["count"])
    ls_company.append(data["_id"])
    ls_count.append(data["count"])
    
df_family_us = pd.DataFrame((zip(ls_company, ls_count)), columns = ['company', 'count'])

In [10]:
# final_df = pd.concat([df_family_de,df_family_cn,df_family_us],axis=0)

In [11]:
# 取總數前15家公司
df_family_de.groupby("company").sum().reset_index().sort_values("count",ascending=False).head(15)

                                              company  count
11                                         Intel Corp     18
19                         Samsung Electronics Co Ltd     18
14                                 LG Electronics Inc     11
25                                          Sony Corp     10
20                                         Siemens AG      9
4   Fraunhofer Gesellschaft zur Forderung der Ange...      8
15                                           NEC Corp      7
26                                    Sony Group Corp      7
27                  Sony Semiconductor Solutions Corp      6
21               Siemens Energy Global GmbH and Co KG      6
8                                    Hyundai Motor Co      5
22                              Siemens Mobility GmbH      5
13                                           Kia Corp      5
18                                  Robert Bosch GmbH      5
1                         Bayerische Motoren Werke AG      4

In [12]:
com_df = df_family_de.groupby("company").sum().reset_index().sort_values("count",ascending=False).head(15)
com_df.reset_index(drop=True, inplace=True)

In [13]:
com_df["count_log"] = com_df["count"].apply(lambda x: np.log(x))
com_df

                                              company  count  count_log
0                                          Intel Corp     18   2.890372
1                          Samsung Electronics Co Ltd     18   2.890372
2                                  LG Electronics Inc     11   2.397895
3                                           Sony Corp     10   2.302585
4                                          Siemens AG      9   2.197225
5   Fraunhofer Gesellschaft zur Forderung der Ange...      8   2.079442
6                                            NEC Corp      7   1.945910
7                                     Sony Group Corp      7   1.945910
8                   Sony Semiconductor Solutions Corp      6   1.791759
9                Siemens Energy Global GmbH and Co KG      6   1.791759
10                                   Hyundai Motor Co      5   1.609438
11                              Siemens Mobility GmbH      5   1.609438
12                                           Kia Corp      5   1.609438
13                                  Robert Bosch GmbH      5   1.609438
14                        Bayerische Motoren Werke AG      4   1.386294

公司名稱正規化

In [14]:
com_df["company"] = com_df.company.apply(lambda x: x.replace(" Inc","")\
                                                    .replace(" Co Ltd","")\
                                                    .replace(" Co. Ltd.","")\
                                                    .replace(" Co., Ltd.","")\
                                                    .replace(" Ltd","")\
                                                    .replace(" Corp","")\
                                                    .replace("..","")\
                                                    .replace("International Business Machines","IBM")\
                                                    .replace("Nippon Telegraph and Telephone","Nippon Telegraph & Tel")\
                                                    .replace("Alibaba Group Holding Ltd","Alibaba")\
                                                    .replace("ZTE Intelligent IoT Technology","ZTE")\
                                                    .replace("AT&T Intellectual Property I LP","AT&T")\
                                                    .replace("Microsoft Technology Licensing LLC","Microsoft")\
                                                    .replace("Telefonaktiebolaget LM Ericsson AB","Ericsson")\
                                                    .replace("Cisco Technology","Cisco Systems")\
                                                    .replace("Verizon Patent and Licensing","Verizon Communications")\
                                                    .replace("Tencent Technology Shenzhen","Tencent Holdings")\
                                                    .replace("China Mobile Communications Group","China Mobile")\
                                                    .replace("Alipay Hangzhou Information Technology","Alibaba Group")\
                                                    .replace("Beijing Xiaomi Mobile Software","Xiaomi")\
                                                    .replace("Nokia Technologies Oy","Nokia")\
                                                    .replace("Hewlett Packard Enterprise Development LP","Hewlett Packard Enterprise")\
                                                    .replace("Taiwan Semiconductor Manufacturing Co TSMC","Taiwan Semiconductor")\
                                                    .replace("Hyundai Motor Co","Hyundai Motor")
                                                    .replace("Bayerische Motoren Werke AG","BMW Group"))

In [15]:
com_df

                                              company  count  count_log
0                                               Intel     18   2.890372
1                                 Samsung Electronics     18   2.890372
2                                      LG Electronics     11   2.397895
3                                                Sony     10   2.302585
4                                          Siemens AG      9   2.197225
5   Fraunhofer Gesellschaft zur Forderung der Ange...      8   2.079442
6                                                 NEC      7   1.945910
7                                          Sony Group      7   1.945910
8                        Sony Semiconductor Solutions      6   1.791759
9                Siemens Energy Global GmbH and Co KG      6   1.791759
10                                      Hyundai Motor      5   1.609438
11                              Siemens Mobility GmbH      5   1.609438
12                                                Kia      5   1.609438
13                                  Robert Bosch GmbH      5   1.609438
14                                          BMW Group      4   1.386294

In [16]:
com_ls = list(com_df.company)

In [17]:
com_ls.remove('Samsung Electronics')

# Data 2019

富比士2000資料

In [18]:
f_data = pd.read_csv("../../patent/code/依年分/Forbes/Forbes_2019.csv")

In [19]:
f_data[f_data["Industry"]=="Semiconductors"]

,Company,Market Value,Revenue,Profits,Assets,Rank,Sector,Industry,Continent,Country,Headquarters,State,CEO,Forbes Webpage,Profits as % of Assets,Profits as % of Revenue
12,Samsung Electronics,272.424,221.506,39.882,304.138,13,Information Technology,Semiconductors,Asia,South Korea,South Korea,NaN,Hyun-Suk Kim,http://www.forbes.com/companies/samsung-electr...,0.131131,0.180049
43,Intel,263.127,70.848,21.053,127.963,44,Information Technology,Semiconductors,North America,United States,California,California,Robert Swan,http://www.forbes.com/companies/intel/,0.164524,0.297157
127,Taiwan Semiconductor,222.396,34.203,11.644,68.000,126,Information Technology,Semiconductors,Asia,Taiwan,Taiwan,NaN,Che Wei,http://www.forbes.com/companies/taiwan-semicon...,0.171235,0.340438
177,Broadcom,126.125,21.310,6.500,72.110,178,Information Technology,Semiconductors,North America,United States,California,California,Hock E. Tan,http://www.forbes.com/companies/broadcom/,0.090140,0.305021
178,SK Hynix,47.645,36.751,14.121,57.052,179,Information Technology,Semiconductors,Asia,South Korea,South Korea,NaN,Seok-Hee Lee,http://www.forbes.com/companies/sk-hynix/,0.247511,0.384234
205,Micron Technology,48.030,29.985,13.060,47.487,206,Information Technology,Semiconductors,North America,United States,Idaho,Idaho,Sanjay Mehrotra,http://www.forbes.com/companies/micron-technol...,0.275023,0.435551
309,Qualcomm,96.692,21.505,2.157,34.246,310,Information Technology,Semiconductors,North America,United States,California,California,Steve Mollenkopf,http://www.forbes.com/companies/qualcomm/,0.062985,0.100302
392,ASML Holding,85.551,12.911,2.979,24.779,393,Information Technology,Semiconductors,Europe,Netherlands,Netherlands,NaN,Peter Wennink,http://www.forbes.com/companies/asml-holding/,0.120223,0.230733
401,Texas Instruments,108.420,15.784,5.537,17.137,402,Information Technology,Semiconductors,North America,United States,Texas,Texas,Richard K. Templeton,http://www.forbes.com/companies/texas-instrume...,0.323102,0.350798
434,Applied Materials,41.726,16.802,3.949,18.922,435,Information Technology,Semiconductors,North America,United States,California,California,Gary Dickerson,http://www.forbes.com/companies/applied-materi...,0.208699,0.235032
528,NVIDIA,113.362,11.716,4.142,13.292,529,Information Technology,Semiconductors,North America,United States,California,California,Jensen Huang,http://www.forbes.com/companies/nvidia/,0.311616,0.353534
576,NXP Semiconductors,33.064,9.407,2.208,21.530,577,Information Technology,Semiconductors,Europe,Netherlands,Netherlands,NaN,Richard Clemmer,http://www.forbes.com/companies/nxp-semiconduc...,0.102555,0.234719
682,Analog Devices,42.279,6.223,1.577,21.828,683,Information Technology,Semiconductors,North America,United States,Massachusetts,Massachusetts,Vincent Roche,http://www.forbes.com/companies/analog-devices/,0.072247,0.253415
703,Lam Research,29.721,10.866,2.902,10.768,704,Information Technology,Semiconductors,North America,United States,California,California,Tim Archer,http://www.forbes.com/companies/lam-research/,0.269502,0.267072
720,Tokyo Electron,26.002,11.908,2.328,10.677,721,Information Technology,Semiconductors,Asia,Japan,Japan,NaN,Toshiki Kawai,http://www.forbes.com/companies/tokyo-electron/,0.218039,0.195499
779,Infineon Technologies,27.317,9.195,1.325,12.722,780,Information Technology,Semiconductors,Europe,Germany,Germany,NaN,Reinhard Ploss,http://www.forbes.com/companies/infineon-techn...,0.104150,0.144100
897,ASE Technology Holding,10.209,12.306,0.838,17.353,898,Information Technology,Semiconductors,Asia,Taiwan,Taiwan,NaN,Chien Chang,http://www.forbes.com/companies/ase-technology...,0.048291,0.068097
905,STMicroelectronics,16.760,9.680,1.294,10.867,906,Information Technology,Semiconductors,Europe,Switzerland,Switzerland,NaN,Jean-Marc Chery,http://www.forbes.com/companies/stmicroelectro...,0.119076,0.133678
1054,MediaTek,14.964,7.895,0.688,13.106,1054,Information Technology,Semiconductors,Asia,Taiwan,Taiwan,NaN,Li Tsai,http://www.forbes.com/companies/mediatek/,0.052495,0.087144
1129,KLA-Tencor,20.327,4.302,1.421,5.605,1129,Information Technology,Semiconductors,North America,United States,California,California,Rick Wallace,http://www.forbes.com/companies/kla-tencor/,0.253524,0.330311
1174,Xilinx,34.164,2.904,0.811,5.355,1174,Information Technology,Semiconductors,North America,United States,California,California,Victor Peng,http://www.forbes.com/companies/xilinx/,0.151447,0.279270
1263,Skyworks Solutions,15.570,3.788,1.133,4.739,1263,Information Technology,Semiconductors,North America,United States,Massachusetts,Massachusetts,Liam Griffin,http://www.forbes.com/companies/skyworks-solut...,0.239080,0.299102
1359,Microchip Technology,23.391,5.022,0.328,18.156,1360,Information Technology,Semiconductors,North America,United States,Arizona,Arizona,Steve Sanghi,http://www.forbes.com/companies/microchip-tech...,0.018066,0.065313
1385,Maxim Integrated Products,16.341,2.497,0.717,3.889,1386,Information Technology,Semiconductors,North America,United States,California,California,Tunç Doluca,http://www.forbes.com/companies/maxim-integrat...,0.184366,0.287145
1416,Advanced Micro Devices,29.938,6.475,0.337,4.556,1417,Information Technology,Semiconductors,North America,United States,California,California,Lisa Su,http://www.forbes.com/companies/advanced-micro...,0.073968,0.052046
1538,ON Semiconductor Corp.,9.319,5.878,0.627,7.588,1539,Information Technology,Semiconductors,North America,United States,Arizona,Arizona,Keith Jackson,http://www.forbes.com/companies/on-semiconductor/,0.082630,0.106669
1599,Renesas Electronics,9.186,6.857,0.494,8.821,1600,Information Technology,Semiconductors,Asia,Japan,Japan,NaN,Bunsei Kure,http://www.forbes.com/companies/renesas-electr...,0.056003,0.072043
1793,Longi Green Energy Technology,12.515,3.065,0.461,5.644,1794,Information Technology,Semiconductors,Asia,China,China,NaN,Zhen Li,http://www.forbes.com/companies/longi-green-en...,0.081680,0.150408
1846,Nanya Technology,6.144,2.532,1.170,5.940,1847,Information Technology,Semiconductors,Asia,Taiwan,Taiwan,NaN,Pei Lee,http://www.forbes.com/companies/nanya-technology/,0.196970,0.462085
1964,Marvell Technology Group,16.379,2.866,-0.179,10.017,1965,Information Technology,Semiconductors,North America,Bermuda,Bermuda,NaN,Sehat Sutardja,http://www.forbes.com/companies/marvell-techno...,-0.017870,-0.062456

## Forbes list  
- 同Industry：1
- 同Sector：2
- 有出現在company list：3
- Company list上有但Forbes沒有：4

In [20]:
forb_ls =[]

for i in com_ls:
    if (f_data["Company"]==i).any():
        if (f_data[f_data.Company==i]["Industry"]=="Semiconductors").any():
            forb_ls.append(1)
        elif (f_data[f_data.Company==i]["Sector"]=="Information Technology").any():
            forb_ls.append(2)
        else:
            forb_ls.append(3)
    else:
        forb_ls.append(4)

In [21]:
forb_ls

[1, 3, 3, 4, 4, 2, 4, 4, 4, 3, 4, 4, 4, 3]

## Company list competitor

In [22]:
competitor_ls=[3, 3, 1, 3, 1, 2, 3, 1, 1, 2, 4, 2, 2, 2]

## 計算NMI

In [23]:
# (labels_true, labels_pred)
nmi = normalized_mutual_info_score(forb_ls,competitor_ls)
ari = adjusted_rand_score(forb_ls,competitor_ls)

print("nmi: ",nmi)
print("ari: ", ari)

nmi:  0.18930069762949098
ari:  -0.11222222222222222